"""thought table

Revision ID: 6e71f302e270
Revises: 
Create Date: 2020-02-29 12:19:12.158186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e71f302e270'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thought',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thought_quotation'), 'thought', ['quotation'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thought_quotation'), table_name='thought')
    op.drop_table('thought')
    # ### end Alembic commands ###
